// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OShaughnessyScreeningCriteria { max_composite_percentile: number | null, max_ps_ratio: number | null, max_evs_ratio: number | null, min_market_cap: number | null, sectors: Array<string> | null, passes_screening_only: boolean | null, }