// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DataSummary { date_range: string | null, stock_count: bigint | null, data_types: Array<string>, key_metrics: Array<string>, completeness_score: number | null, }