// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSummary } from "./DataSummary";
import type { FreshnessStatus } from "./FreshnessStatus";
import type { RefreshPriority } from "./RefreshPriority";

export interface DataFreshnessStatus { data_source: string, status: FreshnessStatus, latest_data_date: string | null, last_refresh: string | null, staleness_days: bigint | null, records_count: bigint, message: string, refresh_priority: RefreshPriority, data_summary: DataSummary, }