// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PiotroskilScreeningCriteria { min_f_score: number | null, min_data_completeness: number | null, sectors: Array<string> | null, min_market_cap: number | null, passes_screening_only: boolean | null, }