// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PiotroskilCriterion {
  name: string,
  category: string,
  weight: number,
  score: number,
  confidence: number,
  data_available: boolean,
  description: string,
}