// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshMode } from "./RefreshMode";
import type { RefreshStatus } from "./RefreshStatus";

export interface RefreshCompletedEvent { mode: RefreshMode, session_id: string, status: RefreshStatus, }