// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshMode } from "./RefreshMode";

export interface RefreshRequestDto { mode: RefreshMode, force_sources: Array<string> | null, initiated_by: string | null, }