// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshMode } from "./RefreshMode";
import type { RefreshStatus } from "./RefreshStatus";

export interface RefreshProgressDto { session_id: string, operation_type: RefreshMode, start_time: string, total_steps: number, completed_steps: number, current_step_name: string | null, current_step_progress: number, overall_progress_percent: number, estimated_completion: string | null, status: RefreshStatus, initiated_by: string, elapsed_minutes: bigint, }