// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshPriority } from "./RefreshPriority";

export interface RefreshRecommendation { action: string, reason: string, estimated_duration: string, priority: RefreshPriority, }