// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ScreeningReadiness { garp_screening: boolean, graham_screening: boolean, valuation_analysis: boolean, blocking_issues: Array<string>, }