// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataFreshnessStatus } from "./DataFreshnessStatus";
import type { FreshnessStatus } from "./FreshnessStatus";
import type { RefreshRecommendation } from "./RefreshRecommendation";
import type { ScreeningReadiness } from "./ScreeningReadiness";

export interface SystemFreshnessReport { overall_status: FreshnessStatus, market_data: DataFreshnessStatus, financial_data: DataFreshnessStatus, calculated_ratios: DataFreshnessStatus, recommendations: Array<RefreshRecommendation>, screening_readiness: ScreeningReadiness, last_check: string, }